### ISSUE TITLE
python manage.py makemigrations 出错

### ISSUE THREAD

**Issue by MALANGBEIJING** [007gzs/dingtalk-django-example#1]
mysqlclient 1.3.13 or newer is required; you have 0.9.3.

**Comment by MALANGBEIJING** [comment]
aliyun-python-sdk-core==2.13.4
aliyun-python-sdk-core-v3==2.13.3
aliyun-python-sdk-kms==2.6.0
amqp==2.4.2
asn1crypto==0.24.0
backports.csv==1.0.7
billiard==3.6.0.0
celery==4.3.0
certifi==2019.3.9
cffi==1.12.2
chardet==3.0.4
crcmod==1.7
cryptography==2.6.1
defusedxml==0.5.0
diff-match-patch==20181111
dingtalk-sdk==1.2.4
Django==2.2
django-import-export==1.2.0
django-redis-cache==2.0.0
django-redis-sessions==0.6.1
django-restframework-apiview==1.3.2
-e git://github.com/darklow/django-suit.git@afcc506e94e5d4018da1ca6352b5b1718abb2f1c#egg=django_suit
djangorestframework==3.9.2
et-xmlfile==1.0.1
gevent==1.4.0
greenlet==0.4.15
hiredis==1.0.0
idna==2.8
jdcal==1.4
jmespath==0.9.4
kombu==4.5.0
mysqlclient==1.4.2
odfpy==1.4.0
openpyxl==2.6.2
oss2==2.6.1
Pillow==6.0.0
pycparser==2.19
pycrypto==2.6.1
pycryptodome==3.8.1
PyMySQL==0.9.3
pytz==2018.9
PyYAML==5.1
redis==3.2.1
requests==2.21.0
six==1.12.0
sqlparse==0.3.0
tablib==0.13.0
urllib3==1.24.1
vine==1.3.0
xlrd==1.2.0
xlwt==1.3.0

**Comment by 007gzs** [comment]
更新到最新代码，然后 `pip install -U -r requirements.txt` 再试下

**Comment by MALANGBEIJING** [comment]
谢谢，你的命令解决了我的问题，
