### ISSUE TITLE
钉钉部分的 local.settings.py 是否需要做相应的改变？

### ISSUE THREAD

**Issue by MALANGBEIJING** [007gzs/dingtalk-django-example#2]
你好，钉钉开放平台不再提供CorpSecret，你可以创建企业内部应用（企业自建），创建完成后使用appKey和appSecret来获取access_token。更多详情可参考“企业内部开发-服务端API-获取access_token”文档。

**Comment by 007gzs** [comment]
sdk已经支持appkey的方式，example还没有修改，可将apps/corp/biz.py 中`SecretClient`替换为 `AppKeyClient` 并传对应构造函数的参数即可
