### ISSUE TITLE
django 跑起来了后，Exception Value: 'ForeignKey' object has no attribute 'rel'

### ISSUE THREAD

**Issue by MALANGBEIJING** [007gzs/dingtalk-django-example#3]
File "/root/.virtualenvs/dingtalk/local/lib/python3.6/site-packages/apiview/filters.py" in __init__
  71.             content_type = ContentType.objects.get_for_model(getattr(field_model, field.name).field.rel.to,

Exception Type: AttributeError at /admin/isv/corp/
Exception Value: 'ForeignKey' object has no attribute 'rel'

**Comment by MALANGBEIJING** [comment]
python 3.6
django 2.2

**Comment by 007gzs** [comment]
先用1.11试下吧，django2没测过，`pip install "django<2"`

**Comment by 007gzs** [comment]
最新版依赖已支持django2
