### ISSUE TITLE
微应用免登好像不起作用

### ISSUE THREAD

**Issue by MALANGBEIJING** [007gzs/dingtalk-django-example#4]
测试微应用，主页地址填写为 http://www.domain.com/static/microapp.html?appId=你的应用ID&corpId=$CORPID$

http://example.com/api/dingtalk/isv/js/config?app_id=dingjo6tnjibgacmg9xb&corp_id=ding52ebc021ae2cfd3a35c2f4657eb6378f

![image](https://user-images.githubusercontent.com/10110269/56400324-edb8e280-6285-11e9-9d1b-2319bd0d20c8.png)
现在的 app_id 不是数字，dingjo6tnjibgacmg9xb，不知道是不是理解错误？

**Comment by 007gzs** [comment]
app_id 传 AgentId，现在AgentId是字符串了么？

**Comment by MALANGBEIJING** [comment]
是的，我把 appKey 错认为是 appId 了，但是免登还是不工作

**Comment by 007gzs** [comment]
你用的是企业内部应用还是ISV服务商应用

**Comment by MALANGBEIJING** [comment]
企业内部微应用

**Comment by MALANGBEIJING** [comment]
![image](https://user-images.githubusercontent.com/10110269/56406153-9412e100-62a2-11e9-9f61-c96669f3585e.png)

**Comment by 007gzs** [comment]
demo里的微应用是ISV的，企业内部的你需要仿照microapp.html写一个

**Comment by MALANGBEIJING** [comment]
好的，谢谢
