### ISSUE TITLE
运行Test Sync Corp测试后显示"code": 10001,     "message": "请先登陆"

### ISSUE THREAD

**Issue by 396858579** [007gzs/dingtalk-django-example#7]
按照提示安装，配置corpid，appkey等参数后，
打开http://www.domain.com/api/dingtalk/corp/test/sync/corp，
显示
"code": 10001,
    "message": "请先登陆"
无法获取导数据。
请问是什么原因啊，谢谢

**Comment by 007gzs** [comment]
先在 http://www.domain.com/admin 登录后，再访问接口
